data = [
    {"name": "Cristiano Ronaldo", "username": "cristiano", "followers": 627_000_000, "category": "Sports (Football)", "country": "Portugal"},
    {"name": "Lionel Messi", "username": "leomessi", "followers": 498_000_000, "category": "Sports (Football)", "country": "Argentina"},
    {"name": "Selena Gomez", "username": "selenagomez", "followers": 428_000_000, "category": "Music/Actress", "country": "USA"},
    {"name": "Kylie Jenner", "username": "kyliejenner", "followers": 399_000_000, "category": "Fashion/Beauty", "country": "USA"},
    {"name": "Dwayne Johnson", "username": "therock", "followers": 397_000_000, "category": "Actor/Fitness", "country": "USA"},
    {"name": "Ariana Grande", "username": "arianagrande", "followers": 380_000_000, "category": "Music", "country": "USA"},
    {"name": "Kim Kardashian", "username": "kimkardashian", "followers": 364_000_000, "category": "Reality TV/Fashion", "country": "USA"},
    {"name": "Beyoncé", "username": "beyonce", "followers": 317_000_000, "category": "Music", "country": "USA"},
    {"name": "Justin Bieber", "username": "justinbieber", "followers": 293_000_000, "category": "Music", "country": "Canada"},
    {"name": "Khloé Kardashian", "username": "khloekardashian", "followers": 310_000_000, "category": "Reality TV/Fashion", "country": "USA"},
    {"name": "Taylor Swift", "username": "taylorswift", "followers": 280_000_000, "category": "Music", "country": "USA"},
    {"name": "Neymar Jr.", "username": "neymarjr", "followers": 214_000_000, "category": "Sports (Football)", "country": "Brazil"},
    {"name": "Kendall Jenner", "username": "kendalljenner", "followers": 291_000_000, "category": "Fashion/Model", "country": "USA"},
    {"name": "Virat Kohli", "username": "virat.kohli", "followers": 265_000_000, "category": "Sports (Cricket)", "country": "India"},
    {"name": "Jennifer Lopez", "username": "jlo", "followers": 252_000_000, "category": "Music/Actress", "country": "USA"},
    {"name": "Nicki Minaj", "username": "nickiminaj", "followers": 220_000_000, "category": "Music", "country": "USA"},
    {"name": "Kourtney Kardashian", "username": "kourtneykardash", "followers": 224_000_000, "category": "Reality TV/Fashion", "country": "USA"},
    {"name": "Zendaya", "username": "zendaya", "followers": 180_000_000, "category": "Actress/Fashion", "country": "USA"},
    {"name": "Gigi Hadid", "username": "gigihadid", "followers": 80_000_000, "category": "Fashion/Model", "country": "USA"},
    {"name": "Chris Hemsworth", "username": "chrishemsworth", "followers": 70_000_000, "category": "Actor", "country": "Australia"},
    {"name": "Shakira", "username": "shakira", "followers": 150_000_000, "category": "Music", "country": "Colombia"},
    {"name": "Priyanka Chopra", "username": "priyankachopra", "followers": 90_000_000, "category": "Actress", "country": "India"},
    {"name": "Will Smith", "username": "willsmith", "followers": 78_000_000, "category": "Actor", "country": "USA"},
    {"name": "LeBron James", "username": "kingjames", "followers": 155_000_000, "category": "Sports (Basketball)", "country": "USA"},
    {"name": "Billie Eilish", "username": "billieeilish", "followers": 110_000_000, "category": "Music", "country": "USA"},
    {"name": "Shawn Mendes", "username": "shawnmendes", "followers": 74_000_000, "category": "Music", "country": "Canada"},
    {"name": "Drake", "username": "champagnepapi", "followers": 142_000_000, "category": "Music", "country": "Canada"},
    {"name": "Zayn Malik", "username": "zayn", "followers": 50_000_000, "category": "Music", "country": "UK"},
    {"name": "David Beckham", "username": "davidbeckham", "followers": 90_000_000, "category": "Sports (Football)", "country": "UK"},
    {"name": "Emma Watson", "username": "emmawatson", "followers": 74_000_000, "category": "Actress", "country": "UK"},
    {"name": "Huda Kattan", "username": "hudabeauty", "followers": 54_000_000, "category": "Beauty", "country": "UAE"},
    {"name": "Miley Cyrus", "username": "mileycyrus", "followers": 210_000_000, "category": "Music", "country": "USA"},
    {"name": "Rihanna", "username": "badgalriri", "followers": 152_000_000, "category": "Music/Beauty", "country": "Barbados"},
    {"name": "Lisa (BLACKPINK)", "username": "lalalalisa_m", "followers": 104_000_000, "category": "Music", "country": "Thailand"},
    {"name": "Jisoo (BLACKPINK)", "username": "sooyaaa__", "followers": 84_000_000, "category": "Music/Actress", "country": "South Korea"},
    {"name": "Jennie (BLACKPINK)", "username": "jennierubyjane", "followers": 90_000_000, "category": "Music", "country": "South Korea"},
    {"name": "Rosé (BLACKPINK)", "username": "roses_are_rosie", "followers": 85_000_000, "category": "Music", "country": "South Korea"},
    {"name": "Robert Downey Jr.", "username": "robertdowneyjr", "followers": 62_000_000, "category": "Actor", "country": "USA"},
    {"name": "Chris Evans", "username": "chrisevans", "followers": 27_000_000, "category": "Actor", "country": "USA"},
    {"name": "Gal Gadot", "username": "gal_gadot", "followers": 113_000_000, "category": "Actress", "country": "Israel"},
    {"name": "Snoop Dogg", "username": "snoopdogg", "followers": 88_000_000, "category": "Music", "country": "USA"},
    {"name": "Ed Sheeran", "username": "teddysphotos", "followers": 46_000_000, "category": "Music", "country": "UK"},
    {"name": "Post Malone", "username": "postmalone", "followers": 31_000_000, "category": "Music", "country": "USA"},
    {"name": "Conor McGregor", "username": "thenotoriousmma", "followers": 48_000_000, "category": "Sports (MMA)", "country": "Ireland"},
    # Add 50 more similar entries...
]
 